from boids.constants import SCREEN_HEIGHT, SCREEN_WIDTH

schema = {
    "_meta": {
        "version": "1.2.4",
    },
    "boundary": {
        "title": "Boundary",
        "fields": {
            "enabled": {
                "title": "Is enabled",
                "type": "bool",
                "default": False,
                "value": False,
            },
            "top_left": {
                "type": "Vector2",
                "x": {
                    "title": "X0",
                    "type": "float",
                    "min": 0.0,
                    "max": SCREEN_WIDTH / 2,
                    "default": 0.0,
                    "value": 0.0,
                },
                "y": {
                    "title": "Y0",
                    "type": "float",
                    "min": 0.0,
                    "max": SCREEN_HEIGHT / 2,
                    "default": 0.0,
                    "value": 0.0,
                },
                "condition": "boundary.fields.enabled.value",
            },
            "bottom_right": {
                "type": "Vector2",
                "x": {
                    "title": "X1",
                    "type": "float",
                    "min": SCREEN_WIDTH / 2,
                    "max": SCREEN_WIDTH,
                    "default": SCREEN_WIDTH,
                    "value": SCREEN_WIDTH,
                },
                "y": {
                    "title": "Y1",
                    "type": "float",
                    "min": SCREEN_HEIGHT / 2,
                    "max": SCREEN_HEIGHT,
                    "default": SCREEN_HEIGHT,
                    "value": SCREEN_HEIGHT,
                },
                "condition": "boundary.fields.enabled.value",
            },
        },
    },
    "boids": {
        "title": "Boids",
        "fields": {
            "count": {
                "title": "Count",
                "type": "int",
                "min": 1,
                "max": 1000,
                "default": 500,
                "value": 500,
            },
            "speed": {
                "title": "Simulation speed",
                "type": "float",
                "min": 0.1,
                "max": 10.0,
                "default": 4.25,
                "value": 4.25,
            },
            "max_speed": {
                "title": "Max speed",
                "type": "float",
                "min": 0.1,
                "max": 100,
                "default": 40.0,
                "value": 40.0,
            },
            "cohesion": {
                "title": "Cohesion, %",
                "type": "int",
                "min": 1,
                "max": 100,
                "default": 15,
                "value": 15,
            },
            "alignment": {
                "title": "Alignment, %",
                "type": "int",
                "min": 1,
                "max": 100,
                "default": 50,
                "value": 50,
            },
            "separation_distance": {
                "title": "Separation distance",
                "type": "int",
                "min": 1,
                "max": 100,
                "default": 35,
                "value": 35,
            },
            "separation_strength": {
                "title": "Separation strength",
                "type": "int",
                "min": 1,
                "max": 100,
                "default": 45,
                "value": 45,
            },
            "turn_factor": {
                "title": "Turn factor",
                "type": "float",
                "min": 1.0,
                "max": 75.0,
                "default": 50.0,
                "value": 50.0,
            },
            "locality_radius": {
                "title": "Locality radius",
                "type": "float",
                "min": 5.0,
                "max": 1000.0,
                "default": 75.0,
                "value": 75.0,
            },
            "colorize_velocity": {
                "title": "Colorize velocity",
                "type": "bool",
                "default": False,
                "value": False,
            },
        },
    },
    "environment": {
        "title": "Environment",
        "fields": {
            "wind_direction": {
                "type": "Vector2",
                "x": {
                    "title": "Wind X",
                    "type": "float",
                    "min": -1.0,
                    "max": 1.0,
                    "default": 0.0,
                    "value": 0.0,
                },
                "y": {
                    "title": "Wind Y",
                    "type": "float",
                    "min": -1.0,
                    "max": 1.0,
                    "default": 0.0,
                    "value": 0.0,
                },
            },
            "wind_strength": {
                "title": "Wind strength",
                "type": "float",
                "min": 0.0,
                "max": 100.0,
                "default": 0.0,
                "value": 0.0,
            },
        },
    },
    "goal": {
        "title": "Goal",
        "fields": {
            "enabled": {
                "title": "Is enabled",
                "type": "bool",
                "default": False,
                "value": False,
            },
            "duration_sec": {
                "title": "Goal duration, s.",
                "type": "int",
                "min": 1,
                "max": 30,
                "default": 5,
                "value": 5,
                "condition": "goal.fields.enabled.value",
            },
            "strength": {
                "title": "Goal strength, %",
                "type": "int",
                "min": 1,
                "max": 100,
                "default": 1,
                "value": 1,
                "condition": "goal.fields.enabled.value",
            },
        },
    },
    "performance": {
        "title": "Performance",
        "fields": {
            "spatial_grid_cell_size": {
                "title": "Spatial grid cell size",
                "type": "int",
                "min": 20,
                "max": 100,
                "default": 50,
                "value": 50,
            },
        },
    },
}
